"""create_initial_financial_models

Revision ID: 7696d40fb558
Revises:
Create Date: 2026-07-21 16:41:53.314282

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7696d40fb558"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'ARS'"), nullable=False),
        sa.Column(
            "current_balance",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "next_income_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("next_income_date", sa.Date(), nullable=True),
        sa.Column(
            "protected_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "safety_buffer",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name=op.f("ck_user_profiles_currency_uppercase")
        ),
        sa.CheckConstraint(
            "next_income_amount >= 0", name=op.f("ck_user_profiles_next_income_amount_non_negative")
        ),
        sa.CheckConstraint(
            "protected_amount >= 0", name=op.f("ck_user_profiles_protected_amount_non_negative")
        ),
        sa.CheckConstraint(
            "safety_buffer >= 0", name=op.f("ck_user_profiles_safety_buffer_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "commitments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "paid",
                "cancelled",
                name="commitment_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("is_recurring", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_commitments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.id"],
            name=op.f("fk_commitments_user_id_user_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commitments")),
    )
    op.create_index(
        "ix_commitments_user_id_due_date_status",
        "commitments",
        ["user_id", "due_date", "status"],
        unique=False,
    )
    op.create_table(
        "purchase_simulations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_name", sa.String(length=120), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("installments", sa.Integer(), nullable=False),
        sa.Column("installment_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("first_installment_date", sa.Date(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "installment_amount > 0",
            name=op.f("ck_purchase_simulations_installment_amount_positive"),
        ),
        sa.CheckConstraint(
            "installments > 0", name=op.f("ck_purchase_simulations_installments_positive")
        ),
        sa.CheckConstraint(
            "total_amount > 0", name=op.f("ck_purchase_simulations_total_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.id"],
            name=op.f("fk_purchase_simulations_user_id_user_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_simulations")),
    )
    op.create_index(
        "ix_purchase_simulations_user_id_created_at",
        "purchase_simulations",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "income",
                "expense",
                name="transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=60), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transactions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.id"],
            name=op.f("fk_transactions_user_id_user_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_user_id_occurred_on",
        "transactions",
        ["user_id", "occurred_on"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_user_id_occurred_on", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_purchase_simulations_user_id_created_at", table_name="purchase_simulations")
    op.drop_table("purchase_simulations")
    op.drop_index("ix_commitments_user_id_due_date_status", table_name="commitments")
    op.drop_table("commitments")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
